# docker-compose.yml

services:
  # The Redis message broker
  redis:
    image: redis:7-alpine
    container_name: redis

  # The FastAPI web server
  api:
    build: .
    container_name: api
    ports:
      - "8000:80"
    volumes:
      - ./ai_code_reviewer:/app/ai_code_reviewer
    # ---- ADD THIS SECTION ----
    env_file:
      - .env
    # --------------------------
    depends_on:
      - redis

  # The Celery background worker
  worker:
    build: .
    container_name: worker
    command: ["/app/.venv/bin/celery", "-A", "ai_code_reviewer.worker.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./ai_code_reviewer:/app/ai_code_reviewer
    # ---- ADD THIS SECTION ----
    env_file:
      - .env
    # --------------------------
    depends_on:
      - redis